Agrego test si falla coverage

diff --git a/.github/workflows/lint-test-coverage.yml b/.github/workflows/lint-test-coverage.yml
--- a/.github/workflows/lint-test-coverage.yml
+++ b/.github/workflows/lint-test-coverage.yml
@@ -37,4 +37,9 @@ jobs:
         run: |
           cd server
           coverage=$(go tool cover -func=../coverage/coverage.out | grep total | awk '{print $3}' | sed 's/%//')
+          
+          if (( $(echo "$coverage < 60.0" | bc -l) )); then
+            echo "Test coverage is below 60%! Failing the job."
+            exit 1
+          fi
           echo "coverage ${coverage}%"
